### PR TITLE
spawn.find_invoking_python: don't trust sys.executable

### PR DESCRIPTION
**Pull request by zmedico**
If the python interpreter is embedded in another process such as uwsgi,
then sys.executable is not reliable.

### CODE REVIEW

**Comment by zmedico** [comment]
In order to handle pythons that aren't cpython, I've updated the patch to test sys.executable with something like `[[ foo == $(python -c 'print("foo")' ]]`.

**Comment by ferringb** [comment]
I'm pretty sure this can be simplified to a spawn_get_output call.  Barring
that, memozing this may be wise- as long as the access test succeeds in
subsequent invocations, then we can trust that the first test still holds
true.

Regarding the os.access call, Solaris is a bit weird for it:
http://bugs.python.org/issue14706 .  in years gone past I tried to protect
against that issue- that said, it may no longer matter.

**Comment by zmedico** [comment]
I've updated it to use os.path.exists (instead of access) and spawn_get_output, and added memoization.

**Comment by zmedico** [comment]
Updated to check if the memoized result still exists before returning it.

**Comment by ferringb** [comment]
I'm pretty sure coverage will go down slightly from this, albeit wouldn't hugely matter in this case.  The change is fine by me- tim, care to do the honors since you own the codebase these days?

**Comment by radhermit** [comment]
Honestly I'd like to make it so find_invoking_python isn't needed, i.e. the bash side doesn't call back into the python side via exec-ing pkgcore scripts but I guess this is fine to help fix the situation in the meantime.

**Comment by radhermit** [comment]
Merged in c3e1df5.

**Pull request closed without merging**
