### PR TITLE
pmaint regen: Support for use.local.desc & pkg_desc_index

### PR DESCRIPTION
**Pull request by mgorny**
To make pmaint a full replacement for egencache.

### CODE REVIEW

**Comment by radhermit** [comment]
Merged with various changes including splitting out the support into separate funcs.

**Comment by radhermit** [comment]
Ah, good call.

**Comment by mgorny** [comment]
You broke return value handling :(.

        if options.use_local_desc:
            ret = update_use_local_desc(repo, out, err)
        if options.pkg_desc_index:
            ret = update_pkg_desc_index(repo, out, err)

Success in a latter call discards errors from former.

**Comment by radhermit** [comment]
I realized that after I committed it but didn't feel like fixing it immediately.

**Comment by radhermit** [comment]
Error handling should be cleaner now.

**Comment by mgorny** [comment]
Still bad. Now pkg_desc_index update won't happen if use.local.desc had any issues.

**Comment by radhermit** [comment]
I kind of prefer it that way if you're explicitly stating you want one or both, it should error out.

**Comment by radhermit** [comment]
Never mind, I think I know what you mean. It's the metadata generation issue for bad ebuilds again I assume.

**Pull request closed without merging**
