### PR TITLE
Update the git rev blame ignore list, add marienz and mgórny

### PR DESCRIPTION
**Pull request by ferringb**
Check the commit messages for overly verbose explanations of what/where/why for the author changes, including an explanation of why tracking this sort of copyright (and how it gets obscured) is relevant.  Fundamentally calling out folks who did the work- even if they don't care now- is part of attracting contributors.

Roughly:
* for the git blame ignore list, this was a manual audit.  For spot checking, it was good enough for me to trace certain things back to '04, which is sufficient for being able to reach back and identify why I fucked something up.
* For mgorny addition to authors, trace the history, arguably it's time.  Worst case, this is a way to add a sense of responsibility to induce future contributions.
* For marienz- VCS and history obscures it, but in tracing code, there are fingerprints and various things nailed over his work, but his work is there and is intrinsic.  I shat most of the code, but they were the backstop on the code side and built the test framework/coverage + did the CLI formatting work.

For the others I've left out from that era, the commit notes my reasoning/tracing for doing so.

### CODE REVIEW

**Comment by thesamesam** [comment]
Yeah, I agree, it's important not to remove old authors.

**Comment by ferringb** [comment]
@arthurzam this should resolve anything lost authors wise; any screwups for the historical is now my actual fault (since I should remember these things) ;)

**Comment by ferringb** [comment]
@thesamesam I don't recall your numbers, but you were starting to show in the list.  Consider this just me doing a quick pass at it, if anyone thinks others should be in there, go nuts.

**Comment by thesamesam** [comment]
Thanks. I don't think I merit being in there at this point, but I'll keep in mind the need to update it when I do get there. This _did_ remind me to go handle https://bugs.gentoo.org/836936 though...

**Review by arthurzam — APPROVED** [review]
Looks fine for me. Let's just wait for @mgorny to confirm his acceptance being named here.

**Comment by arthurzam** [comment]
Confirmed in #pkgcore IRC channel

**Pull request merged**
