### PR TITLE
Support <stabilize-allarches/> in metadata.xml

### PR DESCRIPTION
**Pull request by mgorny**

### CODE REVIEW

**Comment by mgorny** [comment]
Ping.

**Comment by radhermit** [comment]
Thanks, merged.

**Comment by mgorny** [comment]
ETOOLATE. I've already reinvented the wheel, and added `restrict` support. Any suggestion how to go about that in pkgcore? I suppose it would either mean unmaking metadata.xml 'shared' or storing the data along with restrict and filtering on package level.

**Comment by radhermit** [comment]
Yes, the latter is how I'd do it. For each element that you wanted to support restrict attributes for you'd probably have to store a mapping or tuple of restrictions/values. Then the package class that provides an external interface to those values for each package would have to check the restrictions when the attribute was accessed and collapse to the proper values (so probably a jitted attr).

**Pull request closed without merging**
