### PR TITLE
Fixed caching of some classes. Added caching to KeyedAndRestriction

### PR DESCRIPTION
**Pull request by neko259**

### CODE REVIEW

**Comment by ferringb** [comment]
Looks sane offhand, although that's just a surface read...

**Comment by neko259** [comment]
This does not fix all the issues. Much memory is eaten by choices class (or something similar, I don't remember much) that is not immutable because some "reduce" operation is performed on it sometimes. Code is far from perfect so I cannot fully understand how it works and how to reduce memory usage.

**Comment by ferringb** [comment]
The memory explosion you're running into is described here https://github.com/pkgcore/pkgcheck/commit/3a5a8e2abe04bd543b305932f923072189eb159f

**Comment by radhermit** [comment]
Thanks, merged. Sorry for the long wait.

**Pull request closed without merging**
