### PR TITLE
sync/rsync: Clean up temporary timestamp file

### PR DESCRIPTION
**Pull request by mgorny**

### CODE REVIEW

**Comment by mgorny** [comment]
@radhermit?

**Comment by ferringb** [comment]
The intent here makes sense mind you- I'm just picking at the shitty logic/structuring I wrote there and hoping you find a cleaner flow for it.

**Comment by mgorny** [comment]
@radhermit, ping. Can we merge this? I don't think anybody cares enough to improve it beyond that, tbh.

**Comment by radhermit** [comment]
Timestamp handling via context manager done in 138e178528b901bdb74fb17c47fc3797c02d8833, left off on restructuring the logic because atm it makes no sense to me. :smile:

**Comment by radhermit** [comment]
Made the logic a bit cleaner using a separate single file syncing class in 1b1885e2c80db99ce504e314c927f697341d6f2f.

**Pull request closed without merging**
